"""add unique constraint on institution name and country_code

Revision ID: 00c5ae0fb46f
Revises: e446c6ad2ddf
Create Date: 2026-04-01 13:31:02.745249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00c5ae0fb46f'
down_revision: Union[str, Sequence[str], None] = 'e446c6ad2ddf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_institution_name_country', 'institutions', ['name', 'country_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_institution_name_country', 'institutions', type_='unique')
    # ### end Alembic commands ###
