"""add unique constraint on category owner name kind

Revision ID: 73ab276c30df
Revises: 00c5ae0fb46f
Create Date: 2026-04-01 17:43:55.467981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73ab276c30df'
down_revision: Union[str, Sequence[str], None] = '00c5ae0fb46f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_category_owner_name_kind', 'categories', ['owner_id', 'name', 'kind'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_category_owner_name_kind', 'categories', type_='unique')
    # ### end Alembic commands ###
