import {
  ArrowRightLeft,
  Award,
  Baby,
  Banknote,
  Briefcase,
  Bus,
  CircleDollarSign,
  Clapperboard,
  Coins,
  CreditCard,
  Fuel,
  Gift,
  GraduationCap,
  HeartPulse,
  House,
  KeyRound,
  Landmark,
  Laptop,
  Lightbulb,
  PawPrint,
  Percent,
  Plane,
  Scissors,
  Shield,
  ShoppingBag,
  ShoppingBasket,
  Tag,
  TrendingUp,
  Utensils,
  UtensilsCrossed,
  Wrench,
  type LucideIcon,
} from 'lucide-react'

// Maps the kebab-case Lucide names stored on `categories.icon` to their React components
// Only the icons referenced by seeded defaults are imported to keep the bundle small
const ICONS: Record<string, LucideIcon> = {
  'arrow-right-left': ArrowRightLeft,
  award: Award,
  baby: Baby,
  banknote: Banknote,
  briefcase: Briefcase,
  bus: Bus,
  'circle-dollar-sign': CircleDollarSign,
  clapperboard: Clapperboard,
  coins: Coins,
  'credit-card': CreditCard,
  fuel: Fuel,
  gift: Gift,
  'graduation-cap': GraduationCap,
  'heart-pulse': HeartPulse,
  house: House,
  'key-round': KeyRound,
  landmark: Landmark,
  laptop: Laptop,
  lightbulb: Lightbulb,
  'paw-print': PawPrint,
  percent: Percent,
  plane: Plane,
  scissors: Scissors,
  shield: Shield,
  'shopping-bag': ShoppingBag,
  'shopping-basket': ShoppingBasket,
  'trending-up': TrendingUp,
  utensils: Utensils,
  'utensils-crossed': UtensilsCrossed,
  wrench: Wrench,
}

export function getCategoryIcon(iconName: string | null | undefined): LucideIcon {
  if (!iconName) return Tag
  return ICONS[iconName] ?? Tag
}
